Made the following changes:
OsmosysSoftware/user-meta-management pull request #1
Opened 2017-07-12 06:10 UTC by manikanta-osm

1. Fixed warnings and notices
2. Change improper variable names
3. Placed hardcoded nonce lifetime variable in config file

2017-07-14 10:32 UTC, AbijeetP requested changes
Please make the discussed changes.

2017-07-14 10:32 UTC, AbijeetP commented on UserMetaManagement.php
> +	wp_register_script("user-meta-datatable-js", UMM_PLUGIN_URL . '/js/datatables-min.js', array('jquery'));
why is this using double quotes?

2017-07-14 10:32 UTC, AbijeetP commented on UserMetaManagement.php
> +	    } return ($this->parseTemplate(UMM_TEMPLATE . '/users-same-meta-information.php', $user));
why is this in the same line?

2017-07-14 10:32 UTC, AbijeetP commented on UserMetaManagement.php
>      public function updateUserMetaDetails() {
add documentation for the methods.

2017-07-14 10:32 UTC, AbijeetP commented on UserMetaManagement.php
> +    public function nonceLifeTime($time) {
remove 4 hours from constant.

2017-07-14 10:32 UTC, AbijeetP commented on UserMetaManagement.php
> +	wp_register_style('user-meta-font-awesome-css', UMM_PLUGIN_URL . '/css/font-awesome.min.css');
please add `umm` infront of all registrations.

2017-07-14 10:32 UTC, AbijeetP commented on UserMetaManagement.php
> +	add_action('wp_ajax_meta_search', array($this, 'metaSearch')); // Action to search the meta key value combinations.
prefix!

2017-07-14 10:32 UTC, AbijeetP commented on UserMetaManagement.php
> +	add_action('wp_ajax_delete_user_meta', array($this, 'deleteUserMetaDetails')); // Action to delete the user meta information.
comments on top of the statement.

2017-07-14 10:32 UTC, AbijeetP commented on css/style.css
> +thead {
add prefix for classes as well.

2017-07-14 10:32 UTC, AbijeetP commented on css/style.css
> +.btn {
prefix for buttons also!

2017-07-14 10:32 UTC, AbijeetP commented on js/script.js
> +    $(".close-dialog").click(function (){
please add a new line before this.

2017-07-14 10:32 UTC, AbijeetP commented on js/script.js
> +	"columnDefs": [
code is not formatted.

2017-07-14 10:32 UTC, AbijeetP commented on js/script.js
> +            action: 'update_user_meta_data',
write some comments on top of the loops to explain what you are doing.

2017-07-14 10:32 UTC, AbijeetP commented on js/script.js
> +    function designAlertDialogBoxes() {
please get the reference to the currently opened dialog and modify only that dialog.

2017-07-14 10:32 UTC, AbijeetP commented on js/script.js
> +             sortable: false,
please remove " from the code.

2017-07-14 10:32 UTC, AbijeetP commented on template/users-same-meta-information.php
> +		<th>Email<i class="fa fa-fw fa-sort"></i></th>
format code.

2017-07-15 09:54 UTC, manikanta-osm commented on template/users-same-meta-information.php
> +		<th>Email<i class="fa fa-fw fa-sort"></i></th>
Okay Abijeet

2017-07-17 04:23 UTC, AbijeetP requested changes

2017-07-17 04:23 UTC, AbijeetP commented on UserMetaManagement.php
> +    public function UMMAddUserPage() {
please dont prefix function names. They are inside a class ... so it is not an issue that they will ever clash.

2017-07-17 06:01 UTC, AbijeetP approved these changes

2017-07-17 06:01 UTC, merged